name = "canaria-worker"
main = "src/index.ts"
compatibility_date = "2024-12-04"
compatibility_flags = [ "nodejs_compat" ]

[[durable_objects.bindings]]
name = "CANARIA_DO"
class_name = "CanariaSqlDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CanariaSqlDurableObject"]

[observability]
enabled = true
head_sampling_rate = 1

[[rules]]
type = "Text"
globs = ["**/*.html"]
fallthrough = true